language: python
dist: xenial
matrix:
  include:
    - python: 3.9
    - python: 3.8
    - python: 3.7
    - python: 3.6
install:
  - "pip install tox-travis tox==3.14.6 coveralls"
  - "pip install -e ."
script: tox
after_success:
  "coveralls"
